### ISSUE TITLE
DESIGN: Update extension's logo

### ISSUE THREAD

**Issue by sandeep-pani** [HASHCUT69/Blend-n-Run#10]
Update the extension's logo so it doesn't look like a square block.

Currently it looks like this:

![image](https://github.com/HASHCUT69/Blend-n-Run/assets/80412459/9672f44a-6fc9-4771-a715-15feae3e4aa1)

A better design is required. Maybe a circular logo? We are open to creatives.

**Comment by vishwa-X** [comment]
Hey,  Can i work on this ?

**Comment by sathvik-lab** [comment]
Sure. I will assign it to you. Just give an outline before you start designing.

**Comment by vishwa-X** [comment]
Thank you for assigning the task to me.
 I wanted to let you know that I've already created the image and have submitted a pull request with the design.

**Comment by vishwa-X** [comment]
I'm open to any feedback or changes you might have in mind. Please feel free to review the design, and if there are any modifications or adjustments you'd like to see, just let me know.

**Comment by sandeep-pani** [comment]
@vishwa-X The logo looks good, but can you fill-up the entire canvas with the logo? It's too small now. Also, please update the logo in manifest.json so the new logo is visible in the extension palette.

**Comment by vishwa-X** [comment]
yeah sure, I will do it
