### ISSUE TITLE
UPDATE: Update readme file with new screenshots

### ISSUE THREAD

**Issue by sandeep-pani** [HASHCUT69/Blend-n-Run#16]
Update the readme file with screenshots of the latest extension version.

**Comment by mathanraj0601** [comment]
Can you be more elaborate over this issue @sandeep-pani  ?

**Comment by mathanraj0601** [comment]
I understood the issue the new extension has two shortcut keys to paste the code but in the current Readme, it will show only one shortcut (older version).

Can I get assigned?

**Comment by sandeep-pani** [comment]
Yes, make sure the screenshot is similar to the current screenshot, where no other tabs except Google are open in the background and the image should not include the taskbar.

**Comment by mathanraj0601** [comment]
Sure @sandeep-pani !

**Comment by sandeep-pani** [comment]
Hi @mathanraj0601, any updates on this issue? Please let me know if you need any help.

**Comment by mathanraj0601** [comment]
@sandeep-pani, i have changed the Screenshot in my forked repo i need to make the path as relative once i did i will make a PR
