### ISSUE TITLE
GIT: Delete unnecessary branches

### ISSUE THREAD

**Issue by sandeep-pani** [HASHCUT69/Blend-n-Run#17]
Delete unnecessary branches that have been merged already.

**Comment by mathanraj0601** [comment]
I like to work on this @sandeep-pani  can I get assigned for Hacktoberfest? 
Here is my Action plan
- [x] I found the branch which is already merged
Below are the merged branches
- v1.0.0.2
![image](https://github.com/HASHCUT69/Blend-n-Run/assets/98396468/e37d7391-a456-4122-9af0-212a103908ab)
- Bootstrap-fix
![image](https://github.com/HASHCUT69/Blend-n-Run/assets/98396468/672781e0-e8df-48f8-9a6a-137e035307cc)
- v2.0.0.0
![image](https://github.com/HASHCUT69/Blend-n-Run/assets/98396468/a9d4a2f8-c989-45bf-beec-0fd6259d11de)
- [ ] need to remove these branch

**Comment by sandeep-pani** [comment]
@mathanraj0601  Sure, you can delete the three branches you listed.

**Comment by mathanraj0601** [comment]
That's great @sandeep-pani . Is this project participating in hacktoberfest ?

**Comment by sandeep-pani** [comment]
@mathanraj0601 Currently we are not, but we might very soon. Thanks for letting us know about hacktoberfest 😀

**Comment by mathanraj0601** [comment]
@sandeep-pani  If you are planning to participate in hacktoberfest then let me know I will make PR after that : )

**Comment by sandeep-pani** [comment]
@mathanraj0601 We are now participating in hacktoberfest, kindly go through our [Contributing Guidelines](https://github.com/HASHCUT69/Blend-n-Run/blob/master/DOCS/CONTRIBUTING.md) before raising a PR. 

Also, we are not considering this issue as part of hacktoberfest, you can look for issues with the "hacktoberfest" label to contribute in our issues section.

**Comment by mathanraj0601** [comment]
Okay no problem i will contribute : )

**Comment by mathanraj0601** [comment]
@sandeep-pani  With PR we can Modify code and Docs but can't make a PR to delete a branch as It will be deleted by the owner of that branch 
- Forked the repo
- Deleted the branch
- But can't able to raise a PR to reflect the changes in the main repo

The above is the list of branches you need to delete. Go ahead and delete it.
 I will contribute to some other issue and I already found one to work on it waiting for the assigned  to start the work

**Comment by sandeep-pani** [comment]
Okay, thank you so much for trying, I'll delete the branches.

**Comment by mathanraj0601** [comment]
Anytime for contribution : )
